export const GITHUB_CONFIG = {
  GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID,
  GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET,
  GITHUB_OWNER: process.env.GITHUB_OWNER,
  GITHUB_CAP: process.env.GITHUB_CAP,
  GITHUB_PROVIDER_ID: process.env.GITHUB_PROVIDER_ID,
} as const;

export const GOOGLE_CONFIG = {
  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_OWNER: process.env.GOOGLE_OWNER,
  GOOGLE_CAP: process.env.GOOGLE_CAP,
  GOOGLE_PROVIDER_ID: process.env.GOOGLE_PROVIDER_ID,
} as const;
