name: Deploy
on:
  push:
    branches: [dev, cicd/*]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.vars.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "IMAGE_TAG=dev-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: setup
    env:
      TAG: ${{ needs.setup.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.docker
          key: ${{ runner.os }}-docker-${{ hashFiles('**/Dockerfile') }}-${{ needs.setup.outputs.IMAGE_TAG }}
          restore-keys: |
            ${{ runner.os }}-docker-${{ needs.setup.outputs.IMAGE_TAG }}
            ${{ runner.os }}-docker-
            ${{ runner.os }}-
      - name: Build and push image
        run: |
          mkdir -p /tmp/.docker
          docker load < /tmp/.docker/image.tar || true
          docker build -t tinguyen11702/suipass:$TAG .
          docker save tinguyen11702/suipass:$TAG > /tmp/.docker/image.tar
          docker push tinguyen11702/suipass:$TAG
  deploy_to_ec2:
    name: Deploy docker image to EC2
    runs-on: ubuntu-latest
    needs: [setup, build]
    env:
      TAG: ${{ needs.setup.outputs.IMAGE_TAG }}
    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DEV_HOSTNAME }}
          username: ${{ secrets.EC2_DEV_USER }}
          key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
          envs: TAG
          port: 22
          script: |-
            cd ~/deploy
            docker image prune -af
            docker pull tinguyen11702/suipass:$TAG
            docker compose up --build --detach
