name: Deploy
on:
  push:
    branches: [dev, cicd/*]
jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      IMAGE_TAG: ${{ steps.vars.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set outputs
        id: vars
        run: echo "IMAGE_TAG=dev-$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
  build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: setup
    env:
      TAG: ${{ needs.setup.outputs.IMAGE_TAG }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: 'tinguyen11702/suipass:${{ needs.setup.outputs.IMAGE_TAG }}'
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy_to_ec2:
    name: Deploy docker image to EC2
    runs-on: ubuntu-latest
    needs: [setup, build]
    env:
      TAG: ${{ needs.setup.outputs.IMAGE_TAG }}
    steps:
      - name: Deploy on VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_DEV_HOSTNAME }}
          username: ${{ secrets.EC2_DEV_USER }}
          key: ${{ secrets.EC2_DEV_PRIVATE_KEY }}
          envs: TAG
          port: 22
          script: |-
            cd ~/deploy
            docker image prune -af
            docker pull tinguyen11702/suipass:$TAG
            export DEV_TAG=$TAG
            export STAG_TAG=${docker inspect suipass-stag --format='{{.Config.Image}}' | awk -F':' '{print $2}'}
            docker compose up --build --detach
